export const CHECKLIST_LOAD = 'CHECKLIST_LOAD';
export const CHECKLIST_LOAD_SUCCEEDED = 'CHECKLIST_LOAD_SUCCEEDED';
export const CHECKLIST_INPUT_CHANGED = 'CHECKLIST_INPUT_CHANGED';
export const CHECKLIST_ITEM_ADD = 'CHECKLIST_ITEM_ADD';
export const CHECKLIST_ITEM_UPDATED = 'CHECKLIST_ITEM_UPDATED';
export const CHECKLIST_UPDATED = 'CHECKLIST_UPDATED';
export const TOGGLE_CLICKED = 'NOW_TOGGLE#CHECKED_SET';
export const ENTER_KEY_CODE = 13;
export const ESC_KEY_CODE = 27;
export const FILTER = {
	ALL: 'all',
	COMPLETE: 'complete',
	INCOMPLETE: 'incomplete'
};
